/****************************************************************************

Copyright(c) 2016 by IoTelic Technologies. ALL RIGHTS RESERVED.

This Information is proprietary to IoTelic Technologies and MAY NOT
be copied by any method or incorporated into another program without
the express written consent of Iotelic. This Information or any portion
thereof remains the property of Iotelic. The Information contained herein
is believed to be accurate and Iotelic assumes no responsibility or
liability for its use in any way and conveys no license or title under
any patent or copyright and makes no representation or warranty that this
Information is free from patent or copyright infringement.

****************************************************************************/
#ifndef IOT_DBGLOG_PARSER_API_H
#define IOT_DBGLOG_PARSER_API_H

typedef enum {
    IOT_SG_HANDLE_PLC_REG_MSG_ID = 1,
    IOT_SG_HANDLE_PLC_STATE_MSG_ID = 2,
    IOT_SG_STA_SM_ID = 3,
    IOT_SG_STA_HADNLE_METER_R_ID = 4,
    IOT_SG_STA_QUEUE_GW_APP_OTHER_ID = 5,
    IOT_SG_STA_METER_READ_DONE_ID = 6,
    IOT_SG_STA_SM_STARTED_TO_ID = 7,
    IOT_SG_STA_START_SEC_NODE_REG_ID = 8,
    IOT_SG_STA_METER_READ_DONE_SINGLE_ID = 9,
    IOT_SG_STA_START_SEC_NODE_REG_S_ID = 10,
    IOT_SG_STA_STOP_SEC_NODE_REG_S_ID = 11,
    IOT_SG_STA_STOP_SEC_NODE_REG_ID = 12,
    IOT_SG_STA_QUERY_SEC_NODE_REG_ID = 13,
    IOT_SG_STA_QUERY_SEC_NODE_REG_S_ID = 14,
    IOT_SG_STA_CORRECT_TIME_ID = 15,
    IOT_SG_STA_EVENT_ID = 16,

    IOT_SG_CCO_HANDLE_METER_READ = 17,
    IOT_SG_CCO_PRINT_M_DATA = 18,
    IOT_SG_CCO_SRC_METER_ADDR = 19,
    IOT_SG_CCO_DEST_STA_ADDR = 20,
    IOT_SG_CCO_UART_RECV_DATA = 21,
    IOT_SG_PROTO_PRINT_MAC = 22,
    IOT_SG_PROTO_PRINT_DATA = 23,
    IOT_SG_PROTO_PRINT_CMD = 24,
    IOT_SG_PROTO_UART_SEND = 25,
    IOT_SG_CCO_HANDLE_METER_READ_TYPE_ERROR = 26,
    IOT_SG_CCO_HANDLE_METER_READ_NO_RECORD = 27,

    /* concurrent meter reading */
    IOT_SG_CCO_CON_MR_NO_CMD = 28,
    IOT_SG_CCO_SEND_CON_MR_CMD = 29,
    IOT_SG_CCO_SEND_CON_MR_DEST_MAC = 30,
    IOT_SG_CCO_SEND_CON_MR_RSP_NO_CMD_RECORD = 31,
    IOT_SG_CCO_SEND_CON_MR_RSP_DATA = 32,
    IOT_SG_CCO_SEND_CON_MR_NO_RSP = 33,
    IOT_SG_CCO_DROP_METER_DATA_NO_UL_BUF = 34,

    /* secondary node registration */
    IOT_SG_CCO_ADD_SEC_NODE_FAILED = 35,
    IOT_SG_CCO_RECEIVE_SEC_NODE = 36,
    IOT_SG_CCO_SEC_NODE_RECVED = 37,
    IOT_SG_CCO_UL_SEC_NODE_RPT = 38,
    IOT_SG_CCO_SEC_NODE_QUERY = 39,
    IOT_SG_CCO_SEC_NODE_QUERY_SKIP = 40,
    IOT_SG_STA_SEC_NODE_REG_DONE_ID  = 41,

    IOT_SG_CCO_SEC_NODE_REG_S_ID = 42,

    IOT_SG_CCO_EVT_RPT_BUF_FULL = 43,
    IOT_SG_CCO_EVT_RPT_OK = 44,
    IOT_SG_CCO_UL_EVENT_DATA_RPT = 45,
    IOT_SG_CCO_SEC_NODE_REG_ONGING = 46,
    IOT_SG_CCO_SEC_NODE_REG_RPT_DROP_ID = 47,
    IOT_SG_CCO_BUF_REFRESH = 48,
    IOT_SG_CCO_UL_BUF_NO_DATA = 49,
    IOT_SG_CCO_UL_METER_DATA_RPT = 50,
    IOT_SG_CCO_DL_ONLINE_PKT_EXCEED = 51,
    IOT_SG_CCO_TRIGGER_DL_BUF_SEND_DATA = 52,

    IOT_SG_STA_CON_MR_PARSE = 54,
    IOT_SG_STA_HADNLE_CON_MR_TO_ID  = 55,
    IOT_SG_STA_HANDLE_CON_MR_NACK_ID = 56,

    IOT_SG_STA_DRV_PM_MR_ID    = 57,
    IOT_SG_STA_DRV_PM_MR_TO_ID = 58,
    IOT_SG_STA_DRV_PM_CT_ID    = 59,
    IOT_SG_STA_DRV_PM_CT_PEND_ID = 60,
    IOT_SG_STA_DRV_PM_CMT_ID = 61,
    IOT_SG_STA_DRV_PM_CMT_PEND_ID = 62,
    IOT_SG_STA_DRV_PM_MR_PEND_ID = 63,
    IOT_SG_STA_DRV_CT1_MR_ID   = 64,
    IOT_SG_STA_DRV_CT1_MR_PEND_ID = 65,
    IOT_SG_STA_DRV_CT1_CT_ID   = 66,
    IOT_SG_STA_DRV_CT1_CT_PEND_ID = 67,
    IOT_SG_STA_DRV_CT1_MR_TO_ID = 68,
    IOT_SG_STA_DRV_CT1_CMT_PEND_ID = 69,
    IOT_SG_STA_DRV_CT1_CMT_ID = 70,
    IOT_SG_STA_DRV_CT2_MR_ID   = 71,
    IOT_SG_STA_DRV_CT2_MR_PEND_ID = 72,
    IOT_SG_STA_DRV_CT2_CT_ID   = 73,
    IOT_SG_STA_DRV_CT2_CT_PEND_ID = 74,
    IOT_SG_STA_DRV_CT2_MR_TO_ID = 75,
    IOT_SG_STA_DRV_CT2_CMT_PEND_ID = 76,
    IOT_SG_STA_DRV_CT2_CMT_ID = 77,
    IOT_SG_STA_DRV_CT_EXE_ID = 78,

    IOT_SG_CCO_CON_MR_PLC_PKG_SEND_BCAST = 79,
    IOT_SG_CCO_CON_MR_PLC_PKG_RCV_BCAST = 80,
    IOT_SG_CCO_CON_MR_PLC_PKG_SEND_UNICAST = 81,
    IOT_SG_CCO_CON_MR_PLC_PKG_RCV_UNICAST = 82,
    IOT_SG_CCO_SEC_NODE_REG_P1_ID = 83,
    IOT_SG_CCO_SEC_NODE_REG_P2_ID = 84,
    IOT_GW_CCO_SEC_NODE_REG_RPT_DROP_ID = 85,
    IOT_SG_CCO_EVT_CTRL_HANDLE_ID = 86,
    IOT_GW_CCO_EVT_RPT_DROP_ID = 87,
    IOT_SG_CCO_EVT_RPT_DROP_ID = 88,
    IOT_GW_CCO_PLC_PKT_DROP_ID = 89,

    IOT_SG_CCO_DRV_CCTT_SEC_NODE_RPT_ID = 90,
    IOT_SG_STA_DRV_CT1_DEV_DETECT_ID = 91,
    IOT_SG_STA_DRV_CT1_ATTACHED_ID = 92,
    IOT_SG_STA_DRV_CT1_SMC_START_ID = 93,
    IOT_SG_STA_DRV_CT1_SMC_QR_ID = 94,
    IOT_SG_STA_DRV_CT1_SMC_STOP_FAIL_ID = 95,
    IOT_SG_STA_DRV_CT1_SMC_START_FAIL_ID = 96,

    /* dbglog to flash */
    IOT_SG_CCO_DRV_DUMP_STATUS_ID = 97,
    IOT_SG_STA_DUMP_STATUS_1_ID = 98,

    IOT_SG_STA_DRV_PM_DETECT_FINISH = 99,
    IOT_SG_STA_DRV_PM_DETECT_SUCCESS = 100,
    IOT_SG_STA_DRV_PM_DETECT_GET_ADDR = 101,
    IOT_SG_STA_DRV_CT2_SMC_STOP_DUMP_INFO1 = 102,
    IOT_SG_STA_DRV_CT2_SMC_STOP_DUMP_INFO2 = 103,
    IOT_SG_STA_DRV_CT2_SMC_START = 104,
    IOT_SG_STA_DRV_CT2_SMC_ADD_PM = 105,
    IOT_SG_STA_DRV_CT2_UART_CONFIG = 106,
    IOT_SG_STA_DRV_CT2_SMC_MSG_ANALYSE = 107,
    IOT_SG_STA_DRV_CT2_SMC_ADDR_UPDATE = 108,

    /* system timestamp */
    IOT_SG_CCO_TIMESTAMP_STRING = 109,
    IOT_SG_STA_DRV_PM_TIME_ID = 110,
    IOT_SG_STA_DUMP_STATUS_2_ID = 111,

    IOT_SG_CCO_NET_FMT_DELAY_TIME_OUT = 115,
    IOT_SG_CCO_QUERY_SEC_NODE_REG = 116,
    IOT_SG_CCO_LOAD_WL_FROM_PIB = 117,
    IOT_SG_CCO_GET_STA_MAC_BY_INDEX_ERROR = 118,
    IOT_SG_CCO_GET_STA_MAC_BY_INDEX = 119,
    IOT_SG_CCO_HANDLE_PLC_MSG_STA_JOIN_INFO = 120,
    IOT_SG_CCO_HANDLE_PLC_MSG_NW_TOPO_RPT = 121,
    IOT_SG_CCO_HANDLE_PLC_MSG_NW_NEIGHBOR_RPT = 122,
    IOT_SG_CCO_NW_FMT_DONE = 123,
    IOT_SG_CCO_DL_BUF_GET_RETRY_COUNTER_ERR = 124,
    IOT_SG_CCO_START_DL_SEND_TIMER = 125,
    IOT_SG_CCO_START_REFRESH_TIMER_BY_ADD_ENTRY = 126,
    IOT_SG_CCO_STOP_DL_SEND_TIMER = 127,
    IOT_SG_CCO_STOP_REFRESH_TIMER = 128,
    IOT_SG_CCO_UL_BUF_CHANGED = 129,
    IOT_SG_UL_BUF_REPORT_DATA_TO_CCTT = 130,
    IOT_SG_CCO_STOP_UL_SEND_TIMER = 131,
    IOT_SG_CCO_RECV_ACK_REPORT_DATA_TO_CCTT = 132,
    IOT_SG_CCO_CACHE_SG_MR_CMD_FAILED = 134,
    IOT_SG_CCO_CACHE_SG_MR_CMD_OK = 135,
    IOT_SG_CCO_GET_DL_RETRY_CNT = 136,
    IOT_SG_CCO_GET_UL_RETRY_CNT = 137,
    IOT_SG_CCO_CON_MR_EXCEED_MAX_CNT = 138,
    IOT_SG_STA_SEND_CNT_EXCEED_MAX = 139,
    IOT_SG_CCO_SEND_EXCEED_MAX_BCAST_CNT = 140,
    IOT_SG_CCO_UL_BUF_ENTRY_DATA_TYPE = 141,
    IOT_SG_CCO_START_UL_SEND_TIMER = 142,
    IOT_SG_CCO_READ_METER_NO_RSP = 143,
    IOT_SG_CCO_START_DL_SEND_TIMER_BY_REFRESH = 144,
    IOT_SG_CCO_TASK_MSG_ID = 145,
    IOT_SG_CCO_HANDLE_CLI_MSG_ID = 146,
    IOT_SG_CCO_START_BROADCAST_DATA_LEN_ID = 147,
    IOT_SG_CCO_PRINT_CMD_10H_FN = 148,
    IOT_SG_CCO_ADD_SEC_NODE_ADDR = 149,
    IOT_SG_CCO_RMV_SEC_NODE_ADDR = 150,
    IOT_SG_CCO_ROUTER_WORK_MODE = 151,
    IOT_SG_CCO_PRINT_CMD_11H_FN = 152,
    IOT_SG_CCO_ADD_SEC_NODE_DATA_LEN_ERROR = 153,
    IOT_SG_CCO_PRINT_CMD_12H_FN = 154,
    IOT_SG_CCO_CMD_13H_F1_SEC_NODE_DATA_LEN_ERROR = 155,
    IOT_SG_UPGRADE_FILE_TYPE = 156,

    IOT_SG_STA_MR_ERR_ISSUE_NMEM_ID = 158,
    IOT_SG_STA_MR_ERR_CON_NMEM_1_ID = 159,
    IOT_SG_STA_MR_ERR_CON_NMEM_2_ID = 160,
    IOT_SG_STA_MR_ERR_CON_NMEM_3_ID = 161,
    IOT_SG_STA_MR_ERR_CON_TO_ID     = 162,
    IOT_SG_STA_MR_ERR_NON_CON_TO_ID  = 163,
    IOT_SG_STA_MR_ERR_CON_LOST_ITEM_ID = 164,
    IOT_SG_STA_MR_ERR_DRV_BUSY_ID      = 165,

} iot_sg_dbgid;

typedef enum {
    IOT_PING_SEND_ACK = 1,
    IOT_PING_RECV_MSDU = 2,
    IOT_PING_SEND_PING_BCAST = 3,
} iot_ping_dbgid;


typedef enum {
    IOT_PLCUART_SEND_ACK = 1,
    IOT_PLCUART_RECV_MSDU = 2,
    IOT_PLCUART_SEND_MSDU_BCAST = 3,
} iot_plcuart_dbgid;

#endif // !IOT_DBGLOG_PARSER_API_H
